/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class go_Decision */

#ifndef _Included_go_Decision
#define _Included_go_Decision
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     go_Decision
 * Method:    start
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_go_Decision_start
  (JNIEnv *, jobject, jint);

/*
 * Class:     go_Decision
 * Method:    getResponseMove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_go_Decision_getResponseMove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
